# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI3.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(342, 453)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(21, 28, 300, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAccessibleName("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.direct_checkBox = QtWidgets.QCheckBox(self.frame)
        self.direct_checkBox.setGeometry(QtCore.QRect(120, 46, 81, 20))
        self.direct_checkBox.setObjectName("direct_checkBox")
        self.refresh_pushButton = QtWidgets.QPushButton(self.frame)
        self.refresh_pushButton.setGeometry(QtCore.QRect(198, 10, 93, 28))
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.set_pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.set_pushButton_2.setGeometry(QtCore.QRect(198, 43, 93, 28))
        self.set_pushButton_2.setObjectName("set_pushButton_2")
        self.baud_rate_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.baud_rate_lineEdit.setGeometry(QtCore.QRect(11, 44, 61, 26))
        self.baud_rate_lineEdit.setInputMask("")
        self.baud_rate_lineEdit.setMaxLength(6)
        self.baud_rate_lineEdit.setObjectName("baud_rate_lineEdit")
        self.com_port_comboBox = QtWidgets.QComboBox(self.frame)
        self.com_port_comboBox.setGeometry(QtCore.QRect(11, 11, 121, 26))
        self.com_port_comboBox.setObjectName("com_port_comboBox")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(80, 48, 41, 16))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(21, 140, 301, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setAccessibleName("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.events_pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.events_pushButton_3.setGeometry(QtCore.QRect(198, 10, 93, 28))
        self.events_pushButton_3.setObjectName("events_pushButton_3")
        self.version_pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.version_pushButton_4.setGeometry(QtCore.QRect(10, 250, 93, 28))
        self.version_pushButton_4.setObjectName("version_pushButton_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 13, 81, 16))
        self.label_2.setObjectName("label_2")
        self.time_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.time_spinBox.setGeometry(QtCore.QRect(90, 10, 61, 22))
        self.time_spinBox.setMinimum(200)
        self.time_spinBox.setMaximum(999999)
        self.time_spinBox.setObjectName("time_spinBox")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(160, 13, 21, 16))
        self.label_3.setObjectName("label_3")
        self.export_pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.export_pushButton_5.setGeometry(QtCore.QRect(198, 250, 93, 28))
        self.export_pushButton_5.setObjectName("export_pushButton_5")
        self.debug_pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.debug_pushButton_6.setGeometry(QtCore.QRect(104, 250, 93, 28))
        self.debug_pushButton_6.setObjectName("debug_pushButton_6")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 49, 280, 192))
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(23, 8, 71, 16))
        self.label_4.setText("COM Port")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(24, 120, 55, 16))
        self.label_5.setObjectName("label_5")
        self.events_pushButton_3.setEnabled(False)
        self.debug_pushButton_6.setEnabled(False)
        self.export_pushButton_5.setEnabled(False)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.direct_checkBox.setText(_translate("Dialog", "Direct"))
        self.refresh_pushButton.setText(_translate("Dialog", "Refresh"))
        self.set_pushButton_2.setText(_translate("Dialog", "Set"))
        self.baud_rate_lineEdit.setText(_translate("Dialog", "125000"))
        self.label.setText(_translate("Dialog", "Baud"))
        self.events_pushButton_3.setText(_translate("Dialog", "Events"))
        self.version_pushButton_4.setText(_translate("Dialog", "Version"))
        self.label_2.setText(_translate("Dialog", "Sync every"))
        self.label_3.setText(_translate("Dialog", "ms"))
        self.export_pushButton_5.setText(_translate("Dialog", "Export"))
        self.debug_pushButton_6.setText(_translate("Dialog", "Debug"))
        self.label_5.setText(_translate("Dialog", "Data"))
