# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainUI4.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(370, 458)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setText("COM Port")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAccessibleName("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.com_port_comboBox = QtWidgets.QComboBox(self.frame)
        self.com_port_comboBox.setObjectName("com_port_comboBox")
        self.horizontalLayout_2.addWidget(self.com_port_comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.refresh_pushButton = QtWidgets.QPushButton(self.frame)
        self.refresh_pushButton.setObjectName("refresh_pushButton")
        self.horizontalLayout_2.addWidget(self.refresh_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.baud_rate_lineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.baud_rate_lineEdit.sizePolicy().hasHeightForWidth())
        self.baud_rate_lineEdit.setSizePolicy(sizePolicy)
        self.baud_rate_lineEdit.setMaximumSize(QtCore.QSize(73, 24))
        self.baud_rate_lineEdit.setInputMask("")
        self.baud_rate_lineEdit.setMaxLength(6)
        self.baud_rate_lineEdit.setObjectName("baud_rate_lineEdit")
        self.horizontalLayout_7.addWidget(self.baud_rate_lineEdit)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.direct_checkBox = QtWidgets.QCheckBox(self.frame)
        self.direct_checkBox.setObjectName("direct_checkBox")
        self.horizontalLayout_7.addWidget(self.direct_checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.set_pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.set_pushButton_2.setObjectName("set_pushButton_2")
        self.horizontalLayout_7.addWidget(self.set_pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.frame)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setAccessibleName("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.time_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.time_spinBox.setMinimum(200)
        self.time_spinBox.setMaximum(999999)
        self.time_spinBox.setObjectName("time_spinBox")
        self.horizontalLayout_3.addWidget(self.time_spinBox)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.events_pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.events_pushButton_3.setObjectName("events_pushButton_3")
        self.horizontalLayout_3.addWidget(self.events_pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.version_pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.version_pushButton_4.setObjectName("version_pushButton_4")
        self.horizontalLayout_4.addWidget(self.version_pushButton_4)
        self.debug_pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.debug_pushButton_6.setObjectName("debug_pushButton_6")
        self.horizontalLayout_4.addWidget(self.debug_pushButton_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.export_pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.export_pushButton_5.setObjectName("export_pushButton_5")
        self.horizontalLayout_4.addWidget(self.export_pushButton_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.refresh_pushButton.setText(_translate("Dialog", "Refresh"))
        self.baud_rate_lineEdit.setText(_translate("Dialog", "125000"))
        self.label.setText(_translate("Dialog", "Baud"))
        self.direct_checkBox.setText(_translate("Dialog", "Direct"))
        self.set_pushButton_2.setText(_translate("Dialog", "Set"))
        self.label_5.setText(_translate("Dialog", "Data"))
        self.label_2.setText(_translate("Dialog", "Sync every"))
        self.label_3.setText(_translate("Dialog", "ms"))
        self.events_pushButton_3.setText(_translate("Dialog", "Events"))
        self.version_pushButton_4.setText(_translate("Dialog", "Version"))
        self.debug_pushButton_6.setText(_translate("Dialog", "Debug"))
        self.export_pushButton_5.setText(_translate("Dialog", "Export"))
